spring:
  application:
    name: eurekaClient
server:
  port: 8085
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:root@localhost:8082/eureka/,http://root:root@localhost:8083/eureka/,http://root:root@localhost:8084/eureka/