spring:
  application:
    name: eurekaServer
  security:
    basic:
      enabled: true
    user:
      name: root
      password: root
---
spring:
  profiles: eurekaServerOne
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:root@localhost:8083/eureka/,http://root:root@localhost:8084/eureka/
---
spring:
  profiles: eurekaServerTwo
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:root@localhost:8082/eureka/,http://root:root@localhost:8084/eureka/
---
spring:
  profiles: eurekaServerThree
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:root@localhost:8082/eureka/,http://root:root@localhost:8083/eureka/